name: Maven CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Ver archivos del repositorio
        run: ls -la

      - name: Compilar proyecto con Maven
        run: mvn clean compile

      - name: Ejecutar tests unitarios e integracion
        run: mvn verify